project:
  type: website

website:
  title: "ISSS626 Geospatial Analytics and Applications"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
        - text: "1A: Geospatial Data Wrangling with R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01a.html"
        - text: "1B: Choropleth Mapping with R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html"
    right:
      - href: index.qmd
        text: Home
      - icon: linkedin
        href: https://www.linkedin.com/in/tengkokwai/
        aria-label: Linkedin
      - icon: github
        href: https://github.com/davzoku
        aria-label: Github

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual